{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.12.1" %}

{% set build = 0 %}
{% if cuda_compiler_version == "None" %}
{% set build = build + 1000 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/{{ pname }}/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: ffa02c3a308275a9339fbe92add054fac8e9a00cb8fe8c53340094012cb7c633
  patches:
    - patches/0001-cmake-skip-x86-on-non-x86-architectures.patch  # [win]

build:
  number: {{ build }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: default_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  missing_dso_whitelist:
    - "*libcudart.so*"  # [cuda_compiler_version != "None"]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
  # weigh down gpu implementation and give nocuda preference
  track_features:
    - cudatoolkit  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - cmake                     # [win]
    - ninja                     # [win]
    - pkg-config                # [unix]
    - make                      # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
  run:
    - __cuda                    # [cuda_compiler_version != "None"]

test:
  commands:  # [cuda_compiler_version == "None"]
    - hwloc-ls  # [unix and (cuda_compiler_version == "None")]
    - lstopo --version  # [win and (cuda_compiler_version == "None")]
    - hwloc-info --version  # [cuda_compiler_version == "None"]
    - test -f ${PREFIX}/lib/libhwloc${SHLIB_EXT}  # [unix and (cuda_compiler_version == "None")]
    - if not exist %LIBRARY_LIB%\hwloc.lib exit 1  # [win and (cuda_compiler_version == "None")]

about:
  home: https://www.open-mpi.org/projects/hwloc
  dev_url: https://github.com/open-mpi/hwloc
  doc_url: https://www-lb.open-mpi.org/projects/hwloc/doc
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)
  description: |
    This feedstock builds the hwloc library in the `libhwloc` conda package. Different variants of the package are built:
    * *`default`* in the build string: Without CUDA support, installed by default. Install specifically this version with *`conda install libhwloc==*default*`.
    * *`cuda`* in the build string: With CUDA support. Install specifically this version with  *`conda install libhwloc==*cuda*`

extra:
  recipe-maintainers:
    - jan-janssen
    - inducer
    - isuruf
  skip-lints:
    # make check for all builds.
    # commands, if cuda_compiler_version is None.
    - missing_tests
